socket.emit('sendMessageToOperator',{
                  type:"text",
                  item:{
                      key:"",
                      value:""
                  },
                  qs:true,
                  cookieId:localStorage.getItem("cookieId"),
                  allQuestions:[]
});